/* 
 * File:   main.h
 * Author: TABLE 6
 *
 * Created on 23 septembre 2022, 16:52
 */
// C o n fi g u r a ti o n de s èp a r am t re s du c hi p
#define FCY 40000000

#ifndef MAIN_H
#define	MAIN_H
void OperatingSystemLoop(void);
void SetNextRobotStateInAutomaticMode();

#define STATE_ATTENTE 0
#define STATE_ATTENTE_EN_COURS 1
#define STATE_AVANCE 2
#define STATE_AVANCE_EN_COURS 3
#define STATE_TOURNE_GAUCHE 4
#define STATE_TOURNE_GAUCHE_EN_COURS 5
#define STATE_TOURNE_DROITE 6
#define STATE_TOURNE_DROITE_EN_COURS 7
#define STATE_TOURNE_SUR_PLACE_GAUCHE 8
#define STATE_TOURNE_SUR_PLACE_GAUCHE_EN_COURS 9
#define STATE_TOURNE_SUR_PLACE_DROITE 10
#define STATE_TOURNE_SUR_PLACE_DROITE_EN_COURS 11
#define STATE_ARRET 12
#define STATE_ARRET_EN_COURS 13
#define STATE_RECULE 14
#define STATE_RECULE_EN_COURS 15
#define STATE_LEGER_GAUCHE 16
#define STATE_LEGER_GAUCHE_EN_COURS 17
#define STATE_LEGER_DROIT 18
#define STATE_LEGER_DROIT_EN_COURS 19
#define STATE_RALENTIT_GAUCHE 20
#define STATE_RALENTIT_DROIT 21
#define STATE_RALENTIT_GAUCHE_EN_COURS 22
#define STATE_RALENTIT_DROIT_EN_COURS 23
#define STATE_RALENTIT_CENTRE 24
#define STATE_RALENTIT_CENTRE_EN_COURS 25
#define STATE_TOURNE_SUR_SOI 26
#define STATE_TOURNE_SUR_SOI_EN_COURS 27
#define STATE_RECULE 28
#define STATE_RECULE_EN_COURS 29



#define PAS_D_OBSTACLE 0
#define OBSTACLE_A_GAUCHE 1
#define OBSTACLE_A_DROITE 2
#define OBSTACLE_EN_FACE 3
#define OBSTACLE_FLANC_DROIT 4
#define OBSTACLE_FLANC_GAUCHE 5
#define OBSTACLE_A_GAUCHE_PROCHE 6
#define OBSTACLE_A_DROIT_PROCHE 7
#define OBSTACLE_EN_FACE_PROCHE 8
#define OBSTACLE_PARTOUT 9
#define SECURITE 10


#endif	/* MAIN_H */

